### PR TITLE
Japanese Translation

### PR DESCRIPTION
**Pull request by HoengSaan**
I have posted an issue last night because I found some problems in the translations.
But I realized that I can just do the translation instead.
You may notice that some phrase are not being translated, because I don't understand the things itself. (i.e. thcrap) Also, I didn't find where it is from so I can not see the context.
The banner thing, I can't figure out the best translation in Japanese so I decided to left the English instead.
Replay Folder can acutally be translated to リプレイフォルダ but I see many people use replayフォルダ instead.

Related Post: https://github.com/David-JonesDVN/Touhou-Relauncher/issues/13

Update: I will do the further translation when I am free.

### CODE REVIEW

**Comment by David-JonesDVN** [comment]
Hello. I've reviewed the commit but I've noticed that the translation is performed on a version of the resource file before the category redesign, which is why something like "他のゲーム" is still there. If you don't mind, I'll change the base branch of the request to dev, do a merge, and see if I can do the rest myself. I'll post more if there is a problem.

**Comment by David-JonesDVN** [comment]
Alright, I'm pretty new to pull requests, so I don't know if what I did was correct or not, but your repository should have the latest commits now. If you think this is fine and would like to update the rest of the translation in another pull request, let me know and I'll do the merge. If you think there are still some changes, you can still update your branch before I merge.
About your thcrap question, if you've set your thcrap path in the settings tab to a valid location, a "Custom" option will be available in the thcrap profile dropdown list in a game's configuration dialog:
Custom
Clicking that will bring up another dialog for easily selecting patches from the thpatch repository. Unfortunately since the patches are gathered from thpatch, their names and descriptions are untranslatable.

**Comment by HoengSaan** [comment]
I gonna try thcrap today and try to understand it. Than I will do rest of the translation.
To be honestly, I dont know much about github, I have nearly no knowledge in programming and CS.

**Comment by HoengSaan** [comment]
Ok, I think I have pretty much finished the translation, as It was left work before.
I want to make sure how those phrases are gonna be used so I can translate them.
I think it is not very important but I don't want to leave it halfway.
image

image

I have also adjusted the order of <data> to compare with English, it may affect the comparison with the previous Japanese file though.

**Comment by David-JonesDVN** [comment]
The first one is a warning dialog that comes up when the user tries to download a replay for Mountain of Faith while the replay list is full. Mountain of Faith does not support external user replays so the replay downloader has to rename the downloaded replay to fit in an empty slot.
The "Starting Repository" is the link from which thcrap patches are first loaded. The default link is the official repository from thpatch that has links to most of the other game patches, but I put the option there in case the official link breaks and the user needs to use a different mirror.
Basically, thcrap is a program that lets you download and apply different patches to touhou games without modding the game files directly. This can range from translation patches to mods that change the gameplay, graphics, or music. When I originally made this launcher, the UI for the official thcrap client was very confusing, which is why I added that feature into the launcher. It's much better now, but I had already added the feature, so I kept it in.
By the way, I might be gone for the next few days, so I may not be able to release the next version until I get back. Sorry about that.

**Comment by HoengSaan** [comment]
The translation is finished, although some of them remain imperfect like those mentioned before. Other than that, I have adjusted the order of those chunks to better compare with English. I hope it didn't mess up the view.

**Comment by David-JonesDVN** [comment]
Hello again. Looks good to me. I will release the new version after testing the translation and fixing some minor bugs. Thank you for the translation.

**Pull request merged**
